### ISSUE TITLE
memory allocation

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [luoxinliang/gochat#1]
在server.go, 你应该在下面函数中增加对reply的内存分配代码(reply = &Reply{})
func startAccept(args []string) (reply *Reply)
func sendMsgToUser(message *Message) (reply *Reply)
func sendMsg(args []string) (reply *Reply)

**Comment by Gooooodman** [comment]
@feifeiiiiiiiiiii   确实，我刚也发现，我故意出错就异常了 panic 了。  加入了 reply = &Reply{} 就没有出现了。我看了错误提示 怎么没有说这块需要分配.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x45c5bf]
无效的内存地址难道就是指 reply

**Comment by Gooooodman** [comment]
这个例子还有很多问题 呵呵。不过值得学习一下。但是作者还更新吗？

**Comment by feifeiiiiiiiiiii** [comment]
@Gooooodman 是有很多问题 就是不知道作者还更新不了
